services:
  server-db:
    image: postgres:15
    container_name: server-db
    environment:
      POSTGRES_DB: agro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d agro']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data-server-db-development:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d/

  nest-api-tests:
    image: backend-agro-tests
    container_name: nest-api-tests
    build:
      context: .
      dockerfile: DockerfileTest
    depends_on:
      server-db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DB_HOST=server-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_NAME=agro
      - JWT_SECRET=millavesecreta
      - PORT_BACKEND=3000
      - HOST_FRONTED=http://localhost:5173

    command: sh -c "npm run test:unit && npm run test:e2e && npm run build && npm run start:prod"
